name: soulscript
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get_it: ^7.6.7
  internet_connection_checker_plus: ^2.2.0
  hive: ^3.0.0-dev
  isar_flutter_libs: ^4.0.0-dev.13
  shared_preferences: ^2.2.3
  image_picker: ^1.0.7
  uuid: ^4.4.0
  intl: ^0.19.0
  supabase_flutter: ^2.4.0
  fpdart: ^1.1.0
  hive_flutter: ^2.0.0-dev
  path_provider: ^2.1.2
  path: ^1.8.3
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  http: ^1.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
